#!/bin/bash

set -e

git --work-tree "../dotmtxbot" --git-dir "." checkout -f

if ! cmp "../dotmtxbot/config/post-update" "./hooks/post-update" >/dev/null 2>&1; then
    echo "updating post-update hook script"
    cp -a "../dotmtxbot/config/post-update" "./hooks/post-update"
    exec "./hooks/post-update" "$@"
fi

cd "../dotmtxbot"
exec "config/setup.sh"
